### ISSUE TITLE
New Feature: Config File

### ISSUE THREAD

**Issue by amykapernick** [agrinman/tunnelto#5]
Would be great if we could set up a config file with common tunnels (like the ngrok config file)

```
authtoken: xxx
tunnels:
  quokkabot:
    proto: http
    addr: 7071
    subdomain: quokkabot
```
